# version : "3.8"

services:
  ngnix:
    depends_on:
      - web
      - api
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  web:
    depends_on:
      - api
    build : ./client
    develop:
        watch:
          - path: ./client/package.json
            action: rebuild
          - path: ./client/package-lock.json
            action: rebuild
          - path: ./client
            target: /app
            action: sync
    ports:
      - 5173:5173
  api:
    depends_on:
      - db 
        #  condition: service_healthy
    build : ./server
    environment:
      #      postgresql://postgres:postgres@postgres/postgres?sslmode=disable

      DATABASE_URL: postgresql://postgres:postgres@db/mydb?sslmode=disable
      SECRET: test
      GOOGLE_APPLICATION_CREDENTIALS: /app/config/serviceAccountKey.json 
    ports:
      - 8080:8080
    volumes:
        # - ./server:/app
        #  - ./client/dist/:/app/static
        - images:/app/images/
        - ./server/fileserver-8c567-firebase-adminsdk-6k8mq-a3eefe8827.json:/app/config/serviceAccountKey.json 
    develop:
      watch:
        - path: ./server/
          target: /app
          action: sync
        - path: ./server/sql/
          action: rebuild
        - path: ./server/go.mod
          action: rebuild
  db:
    image: postgres:alpine
    restart : always
    environment : 
     - POSTGRES_PASSWORD=postgres
     - PGUSER=postgres
     - POSTGRES_DB=mydb
    expose:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 


volumes:
  pgdata:
  images:

