version : "3.8"

services:
  web:
    depends_on:
      - api
    build : ./client
    volumes:
      - dist:/app/dist
    develop:
        watch:
          - path: ./client/package.json
            action: rebuild
          - path: ./client/package-lock.json
            action: rebuild
          - path: ./client/
            target: /app
            action: sync
  api:
    depends_on:
      - db 
        #  condition: service_healthy
    build : ./server
    environment:
      #      postgresql://postgres:postgres@postgres/postgres?sslmode=disable

      DATABASE_URL: postgresql://postgres:postgres@db/mydb?sslmode=disable
      SECRET: test
        #"host=db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - 8080:8080
    volumes:
        # - ./server:/app
        #  - ./client/dist/:/app/static
        - images:/app/images/
        - dist:/app/static
    develop:
      watch:
        - path: ./server/
          target: /app
          action: sync
        - path: ./client/dist/
          target: /app/static
          action:  sync
        - path: ./server/sql/
          action: rebuild
        - path: ./server/go.mod
          action: rebuild
  db:
    image: postgres:alpine
    restart : always
    environment : 
     - POSTGRES_PASSWORD=postgres
     - PGUSER=postgres
     - POSTGRES_DB=mydb
    expose:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 


volumes:
  pgdata:
  images:
  dist:

