// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: file.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addFileUrl = `-- name: AddFileUrl :one
INSERT INTO files(userId,fileUrl , typeFile, fileName, id )
VALUES ($1, $2, $3, $4,$5)
RETURNING userid, filename, fileurl, typefile, id
`

type AddFileUrlParams struct {
	Userid   uuid.UUID
	Fileurl  string
	Typefile string
	Filename string
	ID       uuid.UUID
}

func (q *Queries) AddFileUrl(ctx context.Context, arg AddFileUrlParams) (File, error) {
	row := q.db.QueryRowContext(ctx, addFileUrl,
		arg.Userid,
		arg.Fileurl,
		arg.Typefile,
		arg.Filename,
		arg.ID,
	)
	var i File
	err := row.Scan(
		&i.Userid,
		&i.Filename,
		&i.Fileurl,
		&i.Typefile,
		&i.ID,
	)
	return i, err
}

const deleteByFileID = `-- name: DeleteByFileID :exec
DELETE  FROM files WHERE id = $1
`

func (q *Queries) DeleteByFileID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteByFileID, id)
	return err
}

const getFileByFileId = `-- name: GetFileByFileId :one
SELECT userid, filename, fileurl, typefile, id FROM files WHERE id = $1
`

func (q *Queries) GetFileByFileId(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByFileId, id)
	var i File
	err := row.Scan(
		&i.Userid,
		&i.Filename,
		&i.Fileurl,
		&i.Typefile,
		&i.ID,
	)
	return i, err
}

const getFileByUserId = `-- name: GetFileByUserId :many
SELECT userid, filename, fileurl, typefile, id FROM files WHERE userId = $1
`

func (q *Queries) GetFileByUserId(ctx context.Context, userid uuid.UUID) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFileByUserId, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.Userid,
			&i.Filename,
			&i.Fileurl,
			&i.Typefile,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
